generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  billingAccount: "1234"
  billingTeamName: "1234"
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
  projectKey: "213"
  projectName: new-jira
  leadUsername: backstage-config-file
  documentationUrl: ""
projectInformation:
  projectName: Mój super nowy projekt
  projectShortName: 1810test43253645645
  buildType: maven
  testInstance: true
  preprodInstance: true
  uatInstance: false
cloudService:
  awsOrAzure: aks
  deploymentLocation: azure_fc1
  acpOrCRP: crp
  displayName: AWS CLUSTER
  version: ""
  productionCluster: false
  subscriptionId: "321321"
  enableStorageProvisioning: true
  ingressSubnetName: ingr
  clusterSubnetName: clu
  adAdminGroupName: admin
  adViewerGroupName: viewer
  adEditorGroupName: ediro
  privateDnsZone: dns
  awsAccountId: ""
  instanceType: ""
  r53HostedZoneDomainName: ""
  sshWorkerKey: ""
  availabilityZones: ""
  az1HarmonizedSubnetId: ""
  az1WorkerSubnetId: ""
  az1PodSubnetId: ""
  az2HarmonizedSubnetId: ""
  az2WorkerSubnetId: ""
  az2PodSubnetId: ""
  az3HarmonizedSubnetId: ""
  az3WorkerSubnetId: ""
  az3PodSubnetId: ""
  workerSecurityGroupIds: ""
  ingressSecurityGroupIds: ""
  customDefinedAutomationAdminRole: ""
automationService:
  jenkinsOrGithubActions: jenkins
  jenkinsWebhook: ""
gheOrganisation:
  organisationName: jarro06
  isNew: false
testingTools:
  sonarQube: true
