generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
projectInformation:
  projectName: Mój super nowy projekt123
  projectShortName: 1810test
  buildType: maven
  testInstance: false
  preprodInstance: true
  uatInstance: true
automationService:
  jenkinsOrGithubActions: gheactions
  jenkinsWebhook: ""
gheOrganisation:
  organisationName: jarro06
