generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  billingAccount: "1234"
  billingTeamName: "1234"
  gheToken: ""
  adpAccessToken: ""
gheOrganisation:
  organisationName: jarro06
projectInformation:
  projectShortName: 1810test43253645645
nexus:
  nexusUrl: "12312432435"
jira:
  adminToken: ""
cloudService:
  awsOrAzure: aks
  deploymentLocation: azure_fc1
